## Parameters

# Genotyping
MIN_FRAC_ALIGN_REF = 0.5
MAX_FRAC_HOM_ALT_READ_DEPTH = 0.25
MAX_FRAC_HET_READ_DEPTH = 0.75
MAX_FRAC_HET_SPLITTERS = 0.75
MAX_FRAC_HOM_REF_SPLITTERS = 0.25
HOM_REF = 'HOM REF'
HET = 'HET'
HOM_ALT = 'HOM ALT'

# BAM
FETCH_FLANK = 20

## Strings

# SVTYPE
SVTYPE_DEL = 'DEL'

# VCF
VCF_SVTYPE = 'SVTYPE'
VCF_END = 'END'
VCF_CIPOS = 'CIPOS'
